# version: "3.8" obsolete
services:
  api:
    # Where we can find the dockerfile (uses relative path)
    build: ./api
    # What to call the container
    container_name: api_c
    # Port mapping (list of mappings)
    ports: 
      - "4000:4000"
    # Volumes we want to create (uses relative paths)
    volumes:
      - ./api:/app
      - /app/node_modules
    
  myblog:
    build: ./myblog
    container_name: myblog_c
    ports:
      - "3000:3000"
    volumes:
      - ./myblog:/app
      - /app/node_modules
    # React properties: start them in interactive mode (react container won't automatically shut down)
    stdin_open: true
    tty: true